### ISSUE TITLE
Sensors not updating

### ISSUE THREAD

**Issue by diegocjorge** [pveiga90/What-s-up-Docker-Updates-Monitor#3]
The sensors don’t appear to update properly. Even when WUD detects an update, the sensor in HASS continues to display that no update is available. To get new data from WUD, I need to reload the integration manually.

What is the polling rate for the sensors? Is there a way to increase it?

**Comment by Deathbot64** [comment]
Did you ever figure out the polling rate?

**Comment by diegocjorge** [comment]
No, but you can use the following automation to reload the integration at your desired interval:

```
mode: single
triggers:
  - trigger: time_pattern
    minutes: "10"
conditions: []
actions:
  - action: homeassistant.reload_config_entry
    metadata: {}
    data: {}
    target:
      entity_id: sensor.dozzle_update_available
```
Note: The `entity_id` can be any entity created by the integration. When the action `homeassistant.reload_config_entry` runs, it reloads the entire integration, not just the specified entity.
